//
// Created by jakub on 19.11.2024.
//

#ifndef ECOSYSTEM_SIMULATION_ANIMALTYPE_H
#define ECOSYSTEM_SIMULATION_ANIMALTYPE_H

enum AnimalType {
    CARNIVORE,
    HERBIVORE
};

#endif //ECOSYSTEM_SIMULATION_ANIMALTYPE_H
