//
// Created by jakub on 17.11.2024.
//

#ifndef ECOSYSTEM_SIMULATION_ACTIONTYPEENUM_H
#define ECOSYSTEM_SIMULATION_ACTIONTYPEENUM_H

enum ActionType {
    EAT,
    MOVE,
    BREED,
    NONE,
    DIE
};

#endif //ECOSYSTEM_SIMULATION_ACTIONTYPEENUM_H
