//
// Created by jakub on 17.11.2024.
//

#ifndef ECOSYSTEM_SIMULATION_ACTIONTYPEENUM_H
#define ECOSYSTEM_SIMULATION_ACTIONTYPEENUM_H

enum ActionType {
    EAT,
    MOVE,
    REPRODUCE,
    NONE,
    DIE,
    ATTACK
};

#endif //ECOSYSTEM_SIMULATION_ACTIONTYPEENUM_H
